name: Format Java code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Java Format
        # You may pin to the exact commit or the version
        # uses: axel-op/googlejavaformat-action@fe78db8a90171b6a836449f8d0e982d5d71e5c5a
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          # Arguments for the Google Java Format executable
          args: --replace
          # Pattern to match the files to be formatted
          files: '**/*.java'
          # Pattern to match the files to be ignored by this action
          files-excluded: ''
          # Set to true to not commit the changes
          skipCommit: false
          # Version of Google Java Format to use
          version: ''
          # Recommended on MacOS machines
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # Commit message
          commitMessage: 'Google Java Format'
